### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_BLE_Creation#7]
I don't think the documentation exists for this library, I'm unable to find it as a subproject of CircuitPython on RTD.

**Comment by tannewt** [comment]
Ah, interesting! I wonder if we should keep this... We are starting to use creation ids more with the wifi-only esp chips. (This repo is for ble though.)

**Comment by tekktrik** [comment]
So do you think this is worth keeping?  Or perhaps archive it?

**Comment by tannewt** [comment]
Yes, let's keep it. I suspect we'll do more BLE-only as our non-USB tools mature. Would you mind doing the docs? Thanks!

**Comment by tekktrik** [comment]
Unfortunately I can't, but @evaherrada or @kattni can!

**Comment by evaherrada** [comment]
Done :)
